[programs.localnet]
solana_app = "2XQVADahsLwN4XGNTKc4i57GhXMXqNN8WsNjABtSNZcK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
